INSERT INTO COIN( 		MARKET_NAME, CREATED, MIN_TRADE_SIZE,
						NOTICE, BASE_CURRENCY, BASE_CURRENCY_LONG,
						IS_ACTIVE, LOGO_URL, MARKET_CURRENCY, MARKET_CURRENCY_LONG)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);


INSERT INTO CURRENCY(	BASE_ADDRESS, COIN_TYPE,
						CURRENCY_LONG, CURRENCY, IS_ACTIVE, MIN_CONFIRMATION, TX_FEE)
VALUES(?, ?, ?, ?, ?, ?, ?);

INSERT INTO MARKET_SUMMARY(		FILL_TYPE, ORDER_TYPE, PRICE, TOTAL, CREATED,
								DISPLAY_MARKET_NAME, HIGH, LOW, OPEN_BUY_ORDERS,
								OPEN_SELL_ORDERS, PREV_DAY, TIME_STAMP, VOLUME)
VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);

INSERT INTO ORDER_BOOK(    ORDER_BOOK_DATETIME, QUANTITY, RATE )
VALUES(?, ?, ?);

INSERT INTO TICKER( 	ASK, BID, LAST) VALUES (?, ?, ?);


