
#-- SEED DATA TO POPULATE DATABASE

INSERT INTO USER_PROFILE(FIRST_NAME, LAST_NAME, CREATED_DATE, DELETE_DATE, IS_ACTIVE)
VALUES('Phouthalang', 'Pygnasak', now(), null, true);

INSERT INTO ACCOUNTS(CURRENCY, EXCHANGE_NAME, USER_PROFILE_ID)
VALUES('BAT', 'BITTREX', '1');
INSERT INTO ACCOUNTS(CURRENCY, EXCHANGE_NAME, USER_PROFILE_ID)
VALUES('ARDR', 'BITTREX', '1');
INSERT INTO ACCOUNTS(CURRENCY, EXCHANGE_NAME, USER_PROFILE_ID)
VALUES('BTC', 'BITTREX', '1');
INSERT INTO ACCOUNTS(CURRENCY, EXCHANGE_NAME, USER_PROFILE_ID)
VALUES('DGB', 'BITTREX', '1');
INSERT INTO ACCOUNTS(CURRENCY, EXCHANGE_NAME, USER_PROFILE_ID)
VALUES('ETH', 'BITTREX', '1');
INSERT INTO ACCOUNTS(CURRENCY, EXCHANGE_NAME, USER_PROFILE_ID)
VALUES('GNT', 'BITTREX', '1');
INSERT INTO ACCOUNTS(CURRENCY, EXCHANGE_NAME, USER_PROFILE_ID)
VALUES('GUP', 'BITTREX', '1');
INSERT INTO ACCOUNTS(CURRENCY, EXCHANGE_NAME, USER_PROFILE_ID)
VALUES('KMD', 'BITTREX', '1');
INSERT INTO ACCOUNTS(CURRENCY, EXCHANGE_NAME, USER_PROFILE_ID)
VALUES('LSK', 'BITTREX', '1');
INSERT INTO ACCOUNTS(CURRENCY, EXCHANGE_NAME, USER_PROFILE_ID)
VALUES('MUSIC', 'BITTREX', '1');
INSERT INTO ACCOUNTS(CURRENCY, EXCHANGE_NAME, USER_PROFILE_ID)
VALUES('NXS', 'BITTREX', '1');
INSERT INTO ACCOUNTS(CURRENCY, EXCHANGE_NAME, USER_PROFILE_ID)
VALUES('NXT', 'BITTREX', '1');
INSERT INTO ACCOUNTS(CURRENCY, EXCHANGE_NAME, USER_PROFILE_ID)
VALUES('PIVX', 'BITTREX', '1');
INSERT INTO ACCOUNTS(CURRENCY, EXCHANGE_NAME, USER_PROFILE_ID)
VALUES('RISE', 'BITTREX', '1');
INSERT INTO ACCOUNTS(CURRENCY, EXCHANGE_NAME, USER_PROFILE_ID)
VALUES('STRAT', 'BITTREX', '1');
INSERT INTO ACCOUNTS(CURRENCY, EXCHANGE_NAME, USER_PROFILE_ID)
VALUES('WAVES', 'BITTREX', '1');
INSERT INTO ACCOUNTS(CURRENCY, EXCHANGE_NAME, USER_PROFILE_ID)
VALUES('XEM', 'BITTREX', '1');
